### ISSUE TITLE
QuickSync encoding does not work despite ffmpeg reporting it

### ISSUE THREAD

**Issue by SavageCore** [SavageCore/new-retro-arcade-neon-attract-screen-tool#13]
Another [user](http://steamcommunity.com/app/465780/discussions/0/343787283758035953/#c343788552539974680) can't use QuickSync.

**Comment by bryancasler** [comment]
Ran into the same bug after trying to render the Attract Screen video with Hardware Acceleration enabled. I never saw the progress bar move, then a few minutes later it notified me that it was finished. However it didn't actually generate a new video. Also, I traced the error back to the fact that the first video in my list had been wiped. So the video file was still there but it was empty. Replacing the file has stopped the error from popping up.

**Comment by SavageCore** [comment]
This appeared to be a bug in ffmpeg, pinning to later version of [node-ffmpeg-installer](https://github.com/kribblo/node-ffmpeg-installer) fixes the issue for me.

**Comment by SavageCore** [comment]
Anyone that feels like testing please download [1.1.1 pre-release](https://github.com/SavageCore/new-retro-arcade-neon-attract-screen-tool/releases/tag/1.1.1-pre) and let me know how you get on!

**Comment by SavageCore** [comment]
Closing as fixed
