### ISSUE TITLE
Render fails when videos contain special characters

### ISSUE THREAD

**Issue by Tarexmd** [SavageCore/new-retro-arcade-neon-attract-screen-tool#15]
[ffmpeg-20161008-230526.txt](https://github.com/SavageCore/new-retro-arcade-neon-attract-screen-tool/files/517919/ffmpeg-20161008-230526.txt)

[videoFiles.txt](https://github.com/SavageCore/new-retro-arcade-neon-attract-screen-tool/files/517922/videoFiles.txt)

**Comment by Tarexmd** [comment]
Smaller log file:
[ffmpeg-20161008-230526.txt](https://github.com/SavageCore/new-retro-arcade-neon-attract-screen-tool/files/517919/ffmpeg-20161008-230526.txt)

**Comment by Tarexmd** [comment]
[videoFiles.txt](https://github.com/SavageCore/new-retro-arcade-neon-attract-screen-tool/files/517922/videoFiles.txt)

**Comment by SavageCore** [comment]
Should be a simple enough fix, escape characters in filename...

**Comment by Tarexmd** [comment]
That fixed it; 8% complete so far. Thanks man I appreciate you tending to the matter personally via chat. Cheers!
