### ISSUE TITLE
Menu not visable

### ISSUE THREAD

**Issue by psychomantis100** [SavageCore/new-retro-arcade-neon-attract-screen-tool#23]
i'm using windows 7 64 bit and the menu doesn't show

**Comment by psychomantis100** [comment]
i think the problem is your program is written for a 32 bit system not 64 bit

**Comment by SavageCore** [comment]
Are you getting the same issue as #22? If so download from the forum thread as there is a workaround version there.  This is only built as 64 bit. What do you mean 32bit?Can you send a screenshot? On 15 Feb 2017 1:01 am, psychomantis100 <notifications@github.com> wrote:i think the problem is your program is written for a 32 bit system not 64 bit

**Comment by psychomantis100** [comment]
![image](https://cloud.githubusercontent.com/assets/25782172/22971473/ad626352-f36d-11e6-911e-34f640cd32b5.png)
 yeah i haven't got any menu or rendering options 

![image](https://cloud.githubusercontent.com/assets/25782172/22971519/d965dd08-f36d-11e6-9dad-a2c3db6533cd.png)
  and what lead me to believe it was for a 32 bit system was the zip file name saying win32 x64 as in windows 32 bit program file x64

**Comment by SavageCore** [comment]
x64 means 64 bit :)

Have you tried running [this](https://mega.nz/#!ZphjUbKK!dQ8WUf3Yux1E43XUT2XD9PDajwoKo0JG26ihkUcPjR4) version? or are you running a release here?

**Comment by psychomantis100** [comment]
i've tried both the test and 1.0.8 and they're both the same problem

**Comment by SavageCore** [comment]
Thanks. Have you had access to the menu at all? It functions ok in terms of assigning videos to the grid?

**Comment by psychomantis100** [comment]
no i have no access to the menu or rendering options i can select videos for the grid but can't render it

**Comment by psychomantis100** [comment]
this version has the menu buttons now 

![image](https://cloud.githubusercontent.com/assets/25782172/22975011/eb08ba8a-f37c-11e6-9fba-e32b4b63f2ba.png)


the version you have provided me with is on the right and 1.0.8 i
![image](https://cloud.githubusercontent.com/assets/25782172/22975058/1785d94e-f37d-11e6-91bc-e1147a16b7ce.png)
s the left

**Comment by SavageCore** [comment]
Thanks for that, if you could do one more thing for me and check [this](https://mega.nz/#!togFyB5D!Y1HvgxaMFZKZGN8vp4-ljHrHOAL1heNBsg-DcDzgXrA) version still runs ok I will add it to the forum thread temporarily.

**Comment by psychomantis100** [comment]
![image](https://cloud.githubusercontent.com/assets/25782172/22975712/8f106a90-f37f-11e6-9e48-a708d83a539c.png)
 yeah it runs okay the left one is the one with the dev console active and the other is the new one and they are good

**Comment by SavageCore** [comment]
Looks like building against a more recent Electron fixes this issue then.

**Comment by psychomantis100** [comment]
an electron?

**Comment by SavageCore** [comment]
That was just for my reference. Electron is the framework this tool is based on.

**Comment by psychomantis100** [comment]
fair enough
