### ISSUE TITLE
cur_dts is invalid.

### ISSUE THREAD

**Issue by TheAutisticGamer** [SavageCore/new-retro-arcade-neon-attract-screen-tool#26]
ok So I got this error when I just started the conversion and it said cur_dts is invalid but I was told not to worry about it. But every time I boot it up. I cant seem to come over and run the conversion. I named the file "Underpants" because I was bored. Heres the log:
[ffmpeg-20180316-201025.log](https://github.com/SavageCore/new-retro-arcade-neon-attract-screen-tool/files/1821128/ffmpeg-20180316-201025.log)

**Comment by SavageCore** [comment]
Does it not generate a video? Or just concerned about seeing this message everytime?

**Comment by TheAutisticGamer** [comment]
It doesn't generate a video. and I get a error sign about it.

**Comment by SavageCore** [comment]
Hmm, I see no failures in that log you provided. What exactly happens and what are the steps to reproduce? If possible...

**Comment by TheAutisticGamer** [comment]
I chose the video. Press start. Then it fails the second I press it

**Comment by SavageCore** [comment]
Well it appears from the log the music is extracted ok, can you check that? `C:\Program Files (x86)\Steam\steamapps\common\New Retro Arcade Neon\NewRetroArcade\Content\Roms\UnderPants.mp3` 

Are no other logs files created? A successful encode results in 2-3 (iirc) files.

**Comment by TheAutisticGamer** [comment]
The Music works fine. im going to check some more things about this

**Comment by TheAutisticGamer** [comment]
eyyy got it done. It somehow could not access the file it was in. Moved it too my desktop and now its working!

**Comment by SavageCore** [comment]
Thanks for the follow-up, sorry I disappeared on you! 

Just to clarify, it could not write to the output video file?

Leaving this open as I'll try and get some time to add checks for write access
